Algoritmo "primeira aula"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Carlos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Renato Antonelle
// Data atual  : 21/03/2023
Var
 n1, n2, soma: real

Inicio
escreva("digite um numero ")
leia (n1)
escreva("digite outro numero")
leia(n2)
soma <- n1 + n2;
escreva(" primeiro numero ",n1)
escreva(" segundo numero ",n2)
escreva ("soma = ", soma)

Fimalgoritmo