Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   :Carlos
// Autor(a)    : Renato Antonelle
// Data atual  : 22/03/2023
Var
n1:real


Inicio
escreva("digite o primeiro valor:")
leia(n1)
se n1>10 entao
escreval(" ")
escreva("É MAIOR QUE 10!")
FIMSE

se n1<10 entao
escreva("É MENOR QUE 10")
FIMSE

se n1=10 entao
escreva("É IGUAL A 10!")
FIMSE
fimalgoritmo