Algoritmo "terceira aula"

// Autor(a)    : Nome do(a) aluno(a)

Var
 n1, n2, area: real
 

Inicio

escreva("digite o tamanho da base do triangulo: ")
leia(n1)
escreva("digite o tamanho da altura do triangulo: ")
leia(n2)
Escreval("-----------------------------")

area <-(n1 * n2)/2;


escreval("A área do seu triangulo é:",area)

escreval("valor da da base",n1)

escreval("valor da altura",n2)
// fim
Fimalgoritmo